### ISSUE TITLE
AttributeError: 'EnsembleDecoderOutput' object has no attribute 'view'

### ISSUE THREAD

**Issue by jdh3577** [OpenNMT/OpenNMT-py#1252]
I am using OpenNMT-0.7.0 version and doing for RNN based pointer-generator (summarization).
I want to use ensemble decoding.
Single decoding is ok, but this error happened..

```
Traceback (most recent call last):
  File "translate.py", line 35, in <module>
    main(opt)
  File "translate.py", line 20, in main
    attn_debug=opt.attn_debug
  File "/root/c3_workspace/onmt/translate/translator.py", line 208, in translate
    batch_data = self.translate_batch(batch, data, attn_debug, fast=self.fast)
  File "/root/c3_workspace/onmt/translate/translator.py", line 335, in translate_batch
    return self._translate_batch(batch, data)
  File "/root/c3_workspace/onmt/translate/translator.py", line 658, in _translate_batch
    if data_type == 'text' and self.copy_attn else None)
  File "/root/c3_workspace/onmt/translate/translator.py", line 727, in _score_target
    memory_lengths=src_lengths, src_map=src_map)
  File "/root/c3_workspace/onmt/translate/translator.py", line 390, in _decode_and_generate
    scores = self.model.generator(dec_out.view(-1, dec_out.size(2)),
AttributeError: 'EnsembleDecoderOutput' object has no attribute 'view'

```

**Comment by vince62s** [comment]
We have no travis test for ensemble ... so we'll need to track down. is it working with 0.6.0 ?

**Comment by vince62s** [comment]
reopen if needed, I would need more info, command line, various tag tests, thanks.

**Comment by javierron** [comment]
Issue persists in 60125c8

Error:
```
Traceback (most recent call last):
  File "translate.py", line 6, in <module>
    main()
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/bin/translate.py", line 48, in main
    translate(opt)
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/bin/translate.py", line 32, in translate
    align_debug=opt.align_debug
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/translate/translator.py", line 362, in translate
    batch, data.src_vocabs, attn_debug
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/translate/translator.py", line 551, in translate_batch
    decode_strategy)
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/translate/translator.py", line 681, in _translate_batch_with_strategy
    batch_offset=decode_strategy.batch_offset)
  File "/pfs/nobackup/home/j/javierro/OpenNMT-py/onmt/translate/translator.py", line 603, in _decode_and_generate
    scores = self.model.generator(dec_out.view(-1, dec_out.size(2)),
AttributeError: 'EnsembleDecoderOutput' object has no attribute 'view'
```

Translate command:

```
python3 translate.py\
    -gpu 0\
    -model $MODEL_PATH_1 $MODEL_PATH_2\
    -src $DATA_SRC\
    -beam_size 50\
    -n_best 50\
    -output $RESULT_PATH/predictions.txt\
    -dynamic_dict
```

Please tell me if any other debugging information is needed
