### ISSUE TITLE
Multi-gpu training with python 2.7

### ISSUE THREAD

**Issue by pdakwale** [OpenNMT/OpenNMT-py#1064]
I am trying to train openNMT-py on 3 gpus using python2.7 and and pytorch 0.4.1, cuda 8.0 and all P40 gpus. I am getting following error in train.py :
 
**mp = torch.multiprocessing.get_context('spawn')
AttributeError: 'module' object has no attribute 'get_context'**

Following is my training call:

**CUDA_VISIBLE_DEVICES=0,1,2 python train.py -data mydata -save_model mymodel -layers 6 -rnn_size 512 -word_vec_size 512 -transformer_ff 2048 -heads 8 -encoder_type transformer -decoder_type transformer -position_encoding -train_steps 200000  -max_generator_batches 2 -dropout 0.1 -batch_size 4096 -batch_type tokens -normalization tokens  -accum_count 2 -optim adam -adam_beta2 0.998 -decay_method noam -warmup_steps 8000 -learning_rate 2 -max_grad_norm 0 -param_init 0  -param_init_glorot -label_smoothing 0.1 -valid_steps 10000 -save_checkpoint_steps 20000 -world_size 3 -gpu_ranks 0 1 2**

I found this thread https://github.com/pytorch/pytorch/issues/334 on pytorch forum concluding that python3 solves the problem but upgrading to python3 currently is not a solution for me due to admin issues. Is there any workaround or solution for training mult-gpu with python2.7 ?

Thanks

**Comment by vince62s** [comment]
no, it won't work with python2.7
it's a requirement for pytorch distributed.
